trigger:
  branches:
    include:
      - main
      - develop

pool:
  vmImage: 'ubuntu-latest'

steps:
# 1. Instalar dependencias y construir
- script: |
    npm install
    npm run build
  displayName: '⚙️ Build React App'

# 2. Publicar carpeta build/ como artifact
- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: 'build'
    artifactName: 'frontend-drop'
  displayName: '📦 Publish frontend-drop'
